// export PROGRESS;

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOADING_BEGIN='LOADING_BEGIN'
export const LOADING_END='LOADING_END'
export const ERROR_OCCURED='ERROR_OCCURED'
export const TRAIN_LOADING='TRAIN_LOADING'
export const FETCH_CITIES='FETCH_CITIES'
export const FETCH_TRAINS_SUCCESS='FETCH_TRAINS_SUCCESS'
export const TRAIN_INSTANCE_LOADING='TRAIN_INSTANCE_LOADING';
export const TRAIN_INSTANCE_LOADING_SUCCESS='TRAIN_INSTANCE_LOADING_SUCCESS'