// export PROGRESS;

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOADING_BEGIN='LOADING_BEGIN'
export const LOADING_END='LOADING_END'
export const ERROR_OCCURED='ERROR_OCCURED'

